from typing import Any, Self

class Dadata:
    def __init__(self, token: str, secret: str = ...) -> None: ...
    def find_by_id(self, name: str, query: str, **kwargs: Any) -> list[dict[str, Any]]: ...
    async def find_by_id_async(self, name: str, query: str, **kwargs: Any) -> list[dict[str, Any]]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, *args: object) -> None: ...
