apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: otel
      username: default
    secureJsonData:
      password: clickhouse
    isDefault: true
    editable: true
